; Dynamic Config - Ark Survival Ascended
; Coloque este arquivo no seu repositório ArkServerDynamic (refs/heads/main/dynamicconfig.ini)
; para que o servidor use as mesmas configurações ao usar -UseDynamicConfig

[ServerSettings]
XPMultiplier=5
TamingSpeedMultiplier=5
HarvestAmountMultiplier=5
ResourcesRespawnPeriodMultiplier=0.5
GlobalTurretDamageLimit=150
MaxNumAlliances=2
HairGrowthSpeedMultiplier=5
PlayerCharacterHealthRecoveryMultiplier=1.2
PlayerCharacterFoodDrainMultiplier=0
PlayerCharacterWaterDrainMultiplier=0
AllowAnyoneBabyImprintCuddle=True
OverrideStructurePlatformPrevention=True
ForceAllowCaveFlyers=True
NonPermanentDiseases=True
AllowHideDamageSourceFromLogs=False
bAllowMultipleUnicorns=True
bForceAllowStructureLocking=True

[/Script/ShooterGame.ShooterGameMode]
; Server
CropGrowthSpeedMultiplier=25
CustomRecipeEffectivenessMultiplier=1.1
FishingLootQualityMultiplier=1.1
MaxNumberOfPlayersInTribe=6
GlobalItemDecompositionTimeMultiplier=0.5
GlobalCorpseDecompositionTimeMultiplier=0.5
; Breeding
BabyMatureSpeedMultiplier=5
BabyCuddleGracePeriodMultiplier=5
BabyCuddleIntervalMultiplier=5
EggHatchSpeedMultiplier=5
MatingSpeedMultiplier=5
MatingIntervalMultiplier=0.75
BabyFoodConsumptionSpeedMultiplier=0.2
; Extras
bUseCorpseLocator=True
bAllowUnlimitedRespecs=True
; Player stats
PerLevelStatsMultiplier_Player[0]=1.5
PerLevelStatsMultiplier_Player[1]=5
PerLevelStatsMultiplier_Player[3]=10
PerLevelStatsMultiplier_Player[4]=100
PerLevelStatsMultiplier_Player[5]=100
PerLevelStatsMultiplier_Player[6]=100
PerLevelStatsMultiplier_Player[7]=2
PerLevelStatsMultiplier_Player[8]=2
PerLevelStatsMultiplier_Player[9]=2.5
PerLevelStatsMultiplier_Player[10]=10
; Dino stats
PerLevelStatsMultiplier_DinoTamed[1]=1.5
PerLevelStatsMultiplier_DinoTamed[3]=1.5
PerLevelStatsMultiplier_DinoTamed[6]=100
PerLevelStatsMultiplier_DinoTamed[8]=1.5
